### ISSUE TITLE
Invalid docblock syntax breaking Datetime.Format API docs

### ISSUE THREAD

**Issue by Sil3ntStorm** [silverstripe/api.silverstripe.org#101]
## Affected Version
SS 4.3

## Description

DateTime.Format in a template used to work fine, now gives broken results like `16/33/2018`
The date is correctly stored in the database and is correctly retrieved if dumped in PHP before used in template.

## Steps to Reproduce

Give the template a datetime from the database and call Format on it in the template code.

The documentation on api.silverstripe.org gives nothing but `the format string` as an explanation for the format parameter (in fact not even that, it's just described as that in a side sentence for the function itself).
Obviously proper format strings that are well known and which people are used to don't work.
One has to Google for the issue (after figuring out the display is what's broken), then find a Stackoverflow Question that then links some ominous changelog which contains some remote mention of it in one of its thousands of lines... Then you have to Google the format to actually find any helpful information.
That's like 10 steps, where one should suffice. Took me like an hour to find the necessary information to change a few characters in the template...

This is ridiculous BS, really pissed off....

**Comment by GuySartorelli** [comment]
Looks fine now - I'm not sure what the original problem was, but the "Format code string. See https://unicode-org.github.io/icu/userguide/format_parse/datetime" message is displaying in http://api.silverstripe.com/4/SilverStripe/ORM/FieldType/DBDatetime.html#method_Format, which I _think_ is what this issue is about.
