### ISSUE TITLE
Update api docs PHP from 7.3 to 8.1

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/api.silverstripe.org#105]
This thing is still running on PHP 7.3!

Update it to PHP 8.1. This is hosted in silverstripe cloud so we know the hosting can support it.

## Prs
**NOTE:** Once this has been merged, either deploy it to [ssapi2](https://silverstripe.cloud/naut/project/ssapi2) or reassign to Guy to do that.
- https://github.com/silverstripe/api.silverstripe.org/pull/108

**Comment by emteknetnz** [comment]
Have merged, assigning back to @GuySartorelli so that it can be deployed

**Comment by GuySartorelli** [comment]
Looks good on UAT. Promoting to prod.

**Comment by GuySartorelli** [comment]
Looks good now that cron has run and rebuilt the site
