### ISSUE TITLE
SegmentField present in documentation but seemingly removed

### ISSUE THREAD

**Issue by cotpat** [silverstripe/api.silverstripe.org#116]
The API docs for v5 currently list a [`SegmentField` class](https://api.silverstripe.org/5/SilverStripe/Forms/SegmentField.html).

However, the "view source" link leads to the [v3 branch](https://github.com/silverstripe/silverstripe-segment-field/blob/3/src/SegmentField.php), and I have been unable to find a corresponding `SegmentField` class in either v4 or v5.

Is it possible that this is a 'leftover' documentation entry?

Kind regards,
Patrick

**Comment by GuySartorelli** [comment]
The 3.x release line of `silverstripe/segment-field` corresponds to the 5.x release of Silverstripe CMS. You can confirm that by checking the dependency constraints in the [composer.json file](https://github.com/silverstripe/silverstripe-segment-field/blob/3/composer.json)
