### ISSUE TITLE
https: toolbar still not working.

### ISSUE THREAD

**Issue by camfindlay** [silverstripe/api.silverstripe.org#13]
Seems there has been PRs to fix this though unsure if it's been deployed yet. The toolbar still seems broken under ssl on the current live site.

**Comment by ss23** [comment]
707414d64735e87a0337a45d913ec6612ac0b648 is the currently deployed commit on live api.silverstripe.org

**Comment by camfindlay** [comment]
@ss23 has the makedoc.sh been run though? Locally I can confirm the toolbar css is included using //path/to/toolbar.css so it will work under https

**Comment by SpiritLevel** [comment]
Toolbar not collapsing well on small devices. 

Other toolbar issues: https://github.com/silverstripe/doc.silverstripe.org/issues/93
