### ISSUE TITLE
3.4 api docs need to be added

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/api.silverstripe.org#26]
I noticed that api is missing docs for 3.4. The needed changes seem fairly obvious and are in:

https://github.com/silverstripe/api.silverstripe.org/blob/master/makedoc.sh
https://github.com/silverstripe/api.silverstripe.org/blob/master/htdocs/.htaccess
https://github.com/silverstripe/api.silverstripe.org/blob/master/conf/apigen/templates/%40layout.latte

Happy to submit PR; I just wanted to first check with those in the know. :)

**Comment by tractorcow** [comment]
At https://github.com/silverstripe/api.silverstripe.org/pull/27

**Comment by SpiritLevel** [comment]
Thanks @tractorcow. Do you know when this goes live ?

**Comment by tractorcow** [comment]
When someone merges it I guess?
