### ISSUE TITLE
Upgrade APIGen

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/api.silverstripe.org#29]
Currently we are using an older version of API Gen. This is due to crashes during generation on the newer API Gen. Probably can be fixed by patching the bad code in framework, but potentially this has also been resolved in the upstream api gen repo.

Currently we are on 2.8 on a hotpatched fork at https://github.com/silverstripe-archive/apigen

We should upgrade to 4.1.2 https://github.com/ApiGen/ApiGen/releases/tag/v4.1.2

**Comment by sminnee** [comment]
This has been superceded by #48.
