### ISSUE TITLE
/search/lookup URLs broken

### ISSUE THREAD

**Issue by sminnee** [silverstripe/api.silverstripe.org#33]
From @spiritlevel

> The parsing of [api:Director] style short codes seems to be generating the correct query:
> api.silverstripe.org/search/lookup/?q=Director&version=3&module=framework
> The problem is that the api site no longer processes such queries. These queries used to work :(

**Comment by sminnee** [comment]
Identified in https://github.com/silverstripe/silverstripe-framework/pull/6895

**Comment by SpiritLevel** [comment]
I think this might be the culprit...

https://github.com/silverstripe/api.silverstripe.org/blob/master/htdocs/.htaccess

Missing lookup.php...

:)

**Comment by robbieaverill** [comment]
The problem is that we're using major version branches for docs site but minor version branches for API site. I've logged an issue to fix all of this up: https://github.com/silverstripe/silverstripe-docsviewer/issues/132
