### ISSUE TITLE
Master docs won't render due to ::class bug

### ISSUE THREAD

**Issue by andrewandante** [silverstripe/api.silverstripe.org#45]
There is now a bug with the MASTER docs where an error:

```
The TokenReflection library threw an exception while parsing the file
```

Occurs when parsing a file using the `MyClass::class` syntax - which is all over SS4. See https://github.com/ApiGen/ApiGen/issues/680 for the issue. There are two ways to solve this: either use the fork of the token reflection: https://github.com/ApiGen/ApiGen/issues/680#issuecomment-220785151 or upgrade to the unstable 5.0.0-rc5 (and PHP7.1).

**Comment by robbieaverill** [comment]
Uh oh! Do you know of any platform changes that might have caused this recently, or what has changed for it to start happening?

**Comment by tractorcow** [comment]
Time to updpate to 5.0.0! :D

**Comment by robbieaverill** [comment]
Reference #29

**Comment by tractorcow** [comment]
Could an upgrade to 4.x work in the mean time?

**Comment by robbieaverill** [comment]
Quite possibly. I think 5.x was pretty fresh at the time and wasn't stable yet.

**Comment by andrewandante** [comment]
First occurrence was September 21st - no deployments or anything at that time. My guess is that a change in Framework around then triggered it - not much crucial that I can see from that time though - maaaaaaaaaaaaybe https://github.com/silverstripe/silverstripe-framework/commit/261302a12150b88068a70f829f7265f31e57f551 but I doubt it.

5.0.0 still isn't stable I don't think - I'd look into the fork of the tokeniser I think. However, 4.x is no longer supported because of the tokeniser issue - so it's a bit of a no-win situation.

For reference, the first files to trip it up were:

- `framework/_register_database.php`
- `framework/src/Core/Startup/ParameterConfirmationToken.php`
- `framework/src/Dev/SapphireTest.php`
- `framework/_config.php`
- `cms/_config.php`
- `assets/_config.php`
- `admin/_config.php`

In that order, all on the 21st. Don't know if that helps much :)

**Comment by tractorcow** [comment]
Is it possible to back-port the tokeniser fix to 4.x? would it be accepted if we do so?

**Comment by tractorcow** [comment]
5.x doesn't look feasible yet https://github.com/ApiGen/ApiGen/issues/1015

**Comment by tractorcow** [comment]
Can we just use another api generator?

**Comment by tractorcow** [comment]
https://github.com/phpDocumentor/phpDocumentor2 maye.

**Comment by sminnee** [comment]
@tractorcow is this still an issue on your Sami version?

**Comment by tractorcow** [comment]
No its fixed.
