### ISSUE TITLE
BUG SAMI API docs [global namespaces] link doesn't work

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/api.silverstripe.org#49]
Link goes to https://ssapi-uat.sites.silverstripe.com/3/.html which doesn't work

**Comment by williamdes** [comment]
Use https://github.com/code-lts/doctum#readme

**Comment by chillu** [comment]
I think this has been fixed now? Clicking "namespaces" on top right leads me to https://api.silverstripe.org/4/namespaces.html
