### ISSUE TITLE
Version dropdown doesn't seem to do anything

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/api.silverstripe.org#58]
In Chrome on MacOS High Sierra.

The dropdown doesn't drop down, however the inspector shows the right options are in the dropdown.

**Comment by tractorcow** [comment]
Are you using multi-monitors? I've found that sometimes the dropdown appears on a DIFFERENT monitor, odd right?

**Comment by robbieaverill** [comment]
Yeah I am (you mean like Fluent does? 😄 ) but I haven't seen a menu show up on other monitors

**Comment by robbieaverill** [comment]
If it works for you we can close

**Comment by tractorcow** [comment]
It works for me but I'm Chrome OS non-high Sierra.
