### ISSUE TITLE
Link to Github source code

### ISSUE THREAD

**Issue by chillu** [silverstripe/api.silverstripe.org#59]
The old API generator inlined the PHP code - and it looks like many people miss that (see https://github.com/silverstripe/silverstripe-framework/issues/7625).

**Comment by ntd** [comment]
I am one of the people missing the good ol' link. I just checked the [online documentation](https://api.silverstripe.org/4/index.html) and the issue is still present.

**Comment by williamdes** [comment]
Do you mean the `at line x` on https://laravel.com/api/5.8/Illuminate/Auth/Events/Authenticated.html ?

**Comment by ntd** [comment]
> Do you mean the `at line x` on https://laravel.com/api/5.8/Illuminate/Auth/Events/Authenticated.html ?

No, the links work fine for laravel: I meant the online SilverStripe API. There the `at line ...` references are just plain text, see e.g.
https://api.silverstripe.org/4/SilverStripe/Admin/ModelAdmin.html

Maybe it just needs to be updated.

**Comment by williamdes** [comment]
Oh yeah it only needs the https://github.com/code-lts/doctum#configuration
`'remote_repository'    => new GitHubRemoteRepository('username/repository', '/path/to/repository'),`

I had to use an external repository for the example ;p

**Comment by chillu** [comment]
@williamdes We already have `remote_repository` in the `project` section of the config, but it doesn't apply? https://github.com/silverstripe/api.silverstripe.org/blob/master/conf/doctum.php#L82

I'm a bit unclear on how we can set this separately for each package, the API docs are a composite of multiple repos (`silverstripe/framework`, `silverstripe/cms` etc)

**Comment by williamdes** [comment]
Looks like it doesn't work on your side
I will have a look ASAP
