### ISSUE TITLE
Link to github in footer

### ISSUE THREAD

**Issue by chillu** [silverstripe/api.silverstripe.org#65]
We do this on docs as well. Without that link, people don't know where to report bugs, and realise they can actually help fixing them ;)

**Comment by williamdes** [comment]
Implemented in 5.3.0-dev phar

**Comment by williamdes** [comment]
Deployed preview: https://williamdes.github.io/mariadb-mysql-kbs/

LGTM :heavy_check_mark:

**Comment by chillu** [comment]
@williamdes Awesome, thanks!

Would it be possible to make the footer link specific to the file path and repo that's currently being shown? It'd be a separate issue, just interested in the possibilities. So https://api.silverstripe.org/4/SilverStripe/AssetAdmin/BatchAction/DeleteAssets.html would point to https://github.com/silverstripe/silverstripe-asset-admin/blob/1/code/BatchAction/DeleteAssets.php, but https://api.silverstripe.org/4/SilverStripe/Admin/LeftAndMain.html would point to https://github.com/silverstripe/silverstripe-admin/blob/1/code/LeftAndMain.php

**Comment by williamdes** [comment]
> @williamdes Awesome, thanks!
> 
> Would it be possible to make the footer link specific to the file path and repo that's currently being shown? It'd be a separate issue, just interested in the possibilities. So https://api.silverstripe.org/4/SilverStripe/AssetAdmin/BatchAction/DeleteAssets.html would point to https://github.com/silverstripe/silverstripe-asset-admin/blob/1/code/BatchAction/DeleteAssets.php, but https://api.silverstripe.org/4/SilverStripe/Admin/LeftAndMain.html would point to https://github.com/silverstripe/silverstripe-admin/blob/1/code/LeftAndMain.php

Ah, this is the code link feature that is fixed in the other pull-request.

The footer is not to add a link to the source code but to add a link to go to a website or Github repo for the api docs for example

To sum up the feature you ask exists and is not the footer one, it should work after merging the other pull-request ;)
