### ISSUE TITLE
dataFieldNames documented but does not exist

### ISSUE THREAD

**Issue by worikgh** [silverstripe/api.silverstripe.org#68]
http://api.silverstripe.org/4/SilverStripe/Forms/FieldList.html#method_dataFieldNames

There is no method dataFieldNames at vendor/silverstripe/framework/src/Forms/FieldList.php
But there is API docs for it
I am using SS 4.0 CMS 4.0

**Comment by kinglozzer** [comment]
That method will be available in 4.1: https://github.com/silverstripe/silverstripe-framework/blob/4/src/Forms/FieldList.php#L140-L148. Is it just a limitation of our docs setup that it shows unreleased methods?

**Comment by dhensby** [comment]
Those docs are for the 4 branch. if you're running the 4.0 branch then you won't have the newer APIs.
