### ISSUE TITLE
Slow image deletion

### ISSUE THREAD

**Issue by worikgh** [silverstripe/api.silverstripe.org#69]
Load a lot of images into the assets into a subfolder/ subfolders
In the Files interface select the folder(s) and "delete" them
Wait.  Wait....

I would extensively test this but I have been waiting 40 minutes for the process to finish.

**Comment by robbieaverill** [comment]
Hi @worikgh, are you talking about using the CMS? This repository is for our API site.

**Comment by worikgh** [comment]
Duh!

**Comment by robbieaverill** [comment]
Please reopen on framework if this is an issue with core functionality
