### ISSUE TITLE
Incorrect return type FieldList::removeByName

### ISSUE THREAD

**Issue by worikgh** [silverstripe/api.silverstripe.org#71]
It is listed at http://api.silverstripe.org/4/SilverStripe/Forms/FieldList.html#method_removeByName as returning $this
It does not.  FieldList::removeByname(..) returns null

**Comment by robbieaverill** [comment]
Thanks. Would you like to PR to the framework to fix the php doc return declaration?

**Comment by robbieaverill** [comment]
Issue moved to [silverstripe/silverstripe-framework #7929](https://github.com/silverstripe/silverstripe-framework/issues/7929) via [**ZenHub**](https://www.zenhub.com/)
