### ISSUE TITLE
GlobalNav Search Broken

### ISSUE THREAD

**Issue by PsukheDelos** [silverstripe/api.silverstripe.org#73]
Recently we updated the SilverStripe.com and SilverStripe.org search from Google Custom Search to Swiftype. The CSS now references a Swiftype specific search input and the JS for Google has been replaced with Swiftype JS. This has broken the GlobalNav search (the search bar that is displayed when you click the search icon in the nav in the top right). 

I believe the fix may be to replace the following lines: 
https://github.com/silverstripe/api.silverstripe.org/blob/master/conf/themes/silverstripe/layout/layout.twig#L48-L51

With: 
```
        <div id="swiftype-search">
            <div class="swiftype-control-searchbox-only" dir="ltr">
                <form class="swiftype-search-box" accept-charset="utf-8">
                    <table cellspacing="0" cellpadding="0" class="swiftype-search-box">
                        <tbody><tr><td class="swiftype-input">
                            <input autocomplete="off" type="text" size="10" class="swiftype-input" name="search" title="search" dir="ltr" spellcheck="false" style="outline: none;" placeholder="Search SilverStripe...">
                        </td>
                            <td class="swiftype-search-button"><input type="submit" value="Search" class="swiftype-search-button" title="search"></td>
                            <td class="swiftype-clear-button"><div class="swiftype-clear-button" title="clear results">&nbsp;</div></td>
                        </tr></tbody>
                    </table>
                </form>
            </div>
        </div>
```

**Comment by clarkepaul** [comment]
As this doesn't seem to be a docs/api/user-help issue, but rather a ss.org global toolbar issue I'll try to get this prioritised through the right team. 

![image](https://user-images.githubusercontent.com/555033/40462544-82636b4c-5f64-11e8-8c02-f3a550beb0f4.png)

Not sure if this is the reason for the break but might be the case... Swiftype code needs to be included in the header which is shared across all the sites rather than being placed within ss.org site.

**Comment by robbieaverill** [comment]
Search is no longer broken. We can track content configuration tweaking here: https://github.com/silverstripe/doc.silverstripe.org/issues/176
