### ISSUE TITLE
Include private statics

### ISSUE THREAD

**Issue by chillu** [silverstripe/api.silverstripe.org#74]
We use it to document our config, so not mentioning these in API docs is very limiting. Example: http://api.silverstripe.org/4/SilverStripe/Assets/File.html doesn't contain `allowed_extensions`.

**Comment by tractorcow** [comment]
Instead of this I suggest to rename to `include private marked as @config`. Having a section of docs describing the config api for each field is a lot more context-rich than simply including private vars.

**Comment by chillu** [comment]
If this brings the task from 30 mins to multiple hours, I'm fine with including all private vars as a first step.
