### ISSUE TITLE
Search is non-functional, and the auto-completer also ceases to work at search.html

### ISSUE THREAD

**Issue by NightJar** [silverstripe/api.silverstripe.org#78]
Behold the results:
http://api.silverstripe.org/4/search.html?search=DataObject
Please also note the non-functional auto-completer in the top-left
And that the adblocker is disabled (top right)

![image](https://user-images.githubusercontent.com/778003/42357785-ac5a7c16-812d-11e8-89b6-ff3abdef4b66.png)

Loading the site on `index.php` sees the auto-completer begin functioning again

![image](https://user-images.githubusercontent.com/778003/42357829-e4af76ca-812d-11e8-9499-d6c58050fe24.png)

Search page is reached by submitting the auto-completer input
type "DataObject" then press enter; although auto-completions exist and are valid, the fact there are more than one matches means it goes to the results page, which then shows no results.

**Comment by chillu** [comment]
@dhensby Regression?

**Comment by dhensby** [comment]
Yep, appears to be :( Looking now

**Comment by dhensby** [comment]
OK - so the value of the search box (or the search box itself) doesn't appear to be available when the sorter is run on this page, which is really strange. I'm looking at a fix now
