### ISSUE TITLE
Improve mobile view

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/api.silverstripe.org#83]
The site looks bad on mobile (I can’t paste a screenshot from my phone right now though)

**Comment by chillu** [comment]
Yep, we managed to make it worse than the default view ... yay.

![image](https://user-images.githubusercontent.com/111025/52979801-2ed67700-343c-11e9-890b-c38bbd0ad6e1.png)

@clarkepaul Might be something the Style Council could tackle in terms of CSS fixes?

**Comment by clarkepaul** [comment]
I would think we could pass this on to Ops team to resolve as its part of the .org bundle. I'll add to our backlog in terms of tracking its progress and suggesting what approach is needed. This is potentially a bigger issue with the sites toolbar.

**Comment by clarkepaul** [comment]
Done a quick inspection of the CSS, seems a quick solution can be done by removing a few lines of CSS for smaller viewports. Added to our backlog to either fix or pass on instructions for the fix by one of the OSers.

**Comment by chillu** [comment]
Since we've switched to the Doctum fork (and removed the toolbar), this has been (accidentally) fixed. I'm sure we could do more around mobile friendly layouts, but it's readable and doesn't have ridiculous margins any more, so ... good enough. 

![Uploading image.png…]()
