### ISSUE TITLE
Abstract classes are not highlighted as being abstract

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/api.silverstripe.org#84]
E.g. https://api.silverstripe.org/4/SilverStripe/Forms/MultiSelectField.html. `SilverStripe\Forms\MultiSelectField` is an abstract class, but there’s nothing to indicate that on the API page for it

**Comment by williamdes** [comment]
Fixed in the next Doctum version, thank you for reporting this !
Ref: https://github.com/code-lts/doctum/commit/4fae085c573a3d75a0a0d059b125620dad506a50
