### ISSUE TITLE
opensearch broken: configuration points to wrong URL

### ISSUE THREAD

**Issue by wernerkrauss** [silverstripe/api.silverstripe.org#85]
I added the "SilverStripe Apidocs" to my search bar in firefox.

Unfortunately it points to sami's default search url `https://api.silverstripe.org/4/index.html?q={searchterm}` instead of `https://api.silverstripe.org/4/search.html?search={searchterm}`

same for SS3 search and Master search.

This can be configured in [/conf/themes/silverstripe/opensearch.twig](https://github.com/silverstripe/api.silverstripe.org/blob/72f10f8a72d5c710e145d82ea5373d8769a83fe8/conf/themes/silverstripe/opensearch.twig)

It might also be useful to add a favicon.

**Comment by robbieaverill** [comment]
Nice catch! Fancy a pull request? The website is open source :-D

**Comment by maxime-rainville** [comment]
Did a quick fix https://github.com/silverstripe/api.silverstripe.org/pull/86

**Comment by wernerkrauss** [comment]
When will api docs be rebuilt to include this fix?

**Comment by robbieaverill** [comment]
I'll deploy this to the UAT site now and have a quick test, then deploy to prod if all good.

**Comment by maxime-rainville** [comment]
The deploy was completed sucessfully, however I'm still getting the old URL in the opensearch.xml file https://api.silverstripe.org/4/opensearch.xml

Is their CDN/Cache in front of the site?

**Comment by robbieaverill** [comment]
CloudFlare probably, can you cache bust to see the new content?

**Comment by maxime-rainville** [comment]
Don't think I've got access to that.

**Comment by robbieaverill** [comment]
Oh, looks like the file is generated as part of the docs generation process. Let's give it a day to regenerate itself.

**Comment by maxime-rainville** [comment]
It's working correctly now.
