### ISSUE TITLE
Protected function not showing on DropdownField

### ISSUE THREAD

**Issue by andrewandante** [silverstripe/api.silverstripe.org#96]
DropdownField has the protected function `getFieldOption()` as shown here: https://github.com/silverstripe/silverstripe-framework/blob/4/src/Forms/DropdownField.php#L97, however this doesn't show up on the API docs: https://api.silverstripe.org/4/SilverStripe/Forms/DropdownField.html

In fact, no protected functions are showing up, I suspect that means there's a bug there.

Functions should also surface their visibility in these docs.

## PRs
- https://github.com/silverstripe/api.silverstripe.org/pull/108

**Comment by GuySartorelli** [comment]
This has been fixed
